'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Select_24Contract01
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''pnlServiceContractListing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlServiceContractListing As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkListStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkListStatus As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''lblRenewalSt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRenewalSt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkListRenewalSt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkListRenewalSt As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''lblNotedSt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotedSt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkListNotedSt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkListNotedSt As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''lblSettlementType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSettlementType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkListSettlementType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkListSettlementType As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''lblCompanyGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyGrp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCompanyGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyGrp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mdlCompanyGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlCompanyGrp As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''imgBtnCompanyGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnCompanyGrp As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblContractGp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContractGp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtContractGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractGrp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mdlContractGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlContractGrp As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''imgBtnContractGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnContractGrp As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClient As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtClientType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mdlPopUpClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlPopUpClient As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''imgbtnClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnClient As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtClientId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSalesman control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSalesman As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSalesman control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesman As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mdlPopUpSalesman control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlPopUpSalesman As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''imgBtnSalesman control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnSalesman As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScheduler As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScheduler As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mdlPopUpScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlPopUpScheduler As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''imgBtnScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnScheduler As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblIncharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIncharge As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtIncharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIncharge As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mdlPopUpIncharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlPopUpIncharge As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''imgBtnIncharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnIncharge As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblTechSupport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechSupport As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTechSupport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTechSupport As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mdlPopUpTechSupport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlPopUpTechSupport As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''imgBtnTechSupport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnTechSupport As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblServiceId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServiceId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtServiceId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtServiceId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mdlPopUpServiceId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlPopUpServiceId As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''imgBtnServiceId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnServiceId As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblContractDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContractDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtContractDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractDt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtContractDtTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractDtTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal1 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtStartDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal3 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtStartDtTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDtTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal4 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblEndDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEndDt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEndDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndDt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal5 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtEndDtTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndDtTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cal6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal6 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblActualEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActualEnd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtActualEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActualEnd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cal7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal7 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtActualEndTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActualEndTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cal8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal8 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSortBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''listSort1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listSort1 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btnSortMove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSortMove As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSortRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSortRemove As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''listSort2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listSort2 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btnPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrint As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnQuit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlPopUpCompanyGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopUpCompanyGrp As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnPnlCompanyGrpClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPnlCompanyGrpClose As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''gvCompanyGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCompanyGrp As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDSCompanyGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDSCompanyGrp As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''pnlPopUpContractGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopUpContractGrp As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnPnlContractGrpClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPnlContractGrpClose As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''gvContractGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvContractGrp As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDSContractGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDSContractGrp As Global.System.Web.UI.WebControls.SqlDataSource
End Class
